export const alias = {
    "numerosBingo": [
        { "numero": 1, "nombre": "El galán" },
        { "numero": 2, "nombre": "Los enamorados" },
        { "numero": 3, "nombre": "El trípode" },
        { "numero": 4, "nombre": "La mesa" },
        { "numero": 5, "nombre": "La mano" },
        { "numero": 6, "nombre": "El valiente" },
        { "numero": 7, "nombre": "El bastón" },
        { "numero": 8, "nombre": "El infinito" },
        { "numero": 9, "nombre": "El zapatero" },
        { "numero": 10, "nombre": "La perfección" },
        { "numero": 11, "nombre": "Los bigotes" },
        { "numero": 12, "nombre": "La docena" },
        { "numero": 13, "nombre": "La docena mala" },
        { "numero": 14, "nombre": "El borracho" },
        { "numero": 15, "nombre": "La quinceañera" },
        { "numero": 16, "nombre": "La dulce" },
        { "numero": 17, "nombre": "La desgracia" },
        { "numero": 18, "nombre": "La mayoría de edad" },
        { "numero": 19, "nombre": "El último adolescente" },
        { "numero": 20, "nombre": "El gran festín" },
        { "numero": 21, "nombre": "La suerte nueva" },
        { "numero": 22, "nombre": "Los patitos" },
        { "numero": 23, "nombre": "San Juan" },
        { "numero": 24, "nombre": "Noche buena" },
        { "numero": 25, "nombre": "La navidad" },
        { "numero": 26, "nombre": "Media docena doble" },
        { "numero": 27, "nombre": "La apuesta" },
        { "numero": 28, "nombre": "El cerro" },
        { "numero": 29, "nombre": "El casi 30" },
        { "numero": 30, "nombre": "La treintena" },
        { "numero": 31, "nombre": "Año nuevo" },
        { "numero": 32, "nombre": "Las cuentas claras" },
        { "numero": 33, "nombre": "La edad de Cristo" },
        { "numero": 34, "nombre": "El burro" },
        { "numero": 35, "nombre": "La mitad más 5" },
        { "numero": 36, "nombre": "La triple docena" },
        { "numero": 37, "nombre": "El camino" },
        { "numero": 38, "nombre": "Las flores" },
        { "numero": 39, "nombre": "Los cuarenta menos uno" },
        { "numero": 40, "nombre": "La madurez" },
        { "numero": 41, "nombre": "El loco" },
        { "numero": 42, "nombre": "La dama" },
        { "numero": 43, "nombre": "El sombrero" },
        { "numero": 44, "nombre": "La casa de madera" },
        { "numero": 45, "nombre": "La cárcel" },
        { "numero": 46, "nombre": "El viudo" },
        { "numero": 47, "nombre": "El aprendiz" },
        { "numero": 48, "nombre": "El barquero" },
        { "numero": 49, "nombre": "El olvidado" },
        { "numero": 50, "nombre": "Medio siglo" },
        { "numero": 51, "nombre": "El abuelo" },
        { "numero": 52, "nombre": "El juego" },
        { "numero": 53, "nombre": "La serenata" },
        { "numero": 54, "nombre": "La cueva" },
        { "numero": 55, "nombre": "Los gemelos" },
        { "numero": 56, "nombre": "El aventurero" },
        { "numero": 57, "nombre": "El caminante" },
        { "numero": 58, "nombre": "El viejo lobo" },
        { "numero": 59, "nombre": "La última lágrima" },
        { "numero": 60, "nombre": "La década feliz" },
        { "numero": 61, "nombre": "La paciencia" },
        { "numero": 62, "nombre": "La sabia" },
        { "numero": 63, "nombre": "El jubilado" },
        { "numero": 64, "nombre": "El banquete" },
        { "numero": 65, "nombre": "La esperanza" },
        { "numero": 66, "nombre": "El diablo" },
        { "numero": 67, "nombre": "El poeta" },
        { "numero": 68, "nombre": "El maestro" },
        { "numero": 69, "nombre": "El juguetón" },
        { "numero": 70, "nombre": "El decano" },
        { "numero": 71, "nombre": "La escalera rota" },
        { "numero": 72, "nombre": "El docente" },
        { "numero": 73, "nombre": "El filósofo" },
        { "numero": 74, "nombre": "El hospital" },
        { "numero": 75, "nombre": "El mayor" }
    ]
}
